
[Recipes]
	#[Enable/Disable] Gold Apple Sapling Recipe [true/false] | [Default: false]
	GoldAppleSaplingRecipe = false
	#[Enable/Disable] Emerald Apple Sapling Recipe [true/false] | [Default: false]
	EmeraldAppleSaplingRecipe = false
	#[Enable/Disable] Notch Apple Recipe [true/false] | [Default: false]
	NotchAppleRecipe = false

["Plants Config"]
	#[Enable/Disable] Right Click Harvest on Any Apple Plant [true/false] | [Default: true]
	useEasyHarvest = true
	#[Enable/Disable] Bonemeal use on Any Apple Plant (Override Individual Options) [true/false] | [Default: true]
	allowBonemeal = true
	#[Enable/Disable] Bonemeal use on Apple Plants [true/false] | [Default: true]
	allowAppleBonemeal = true
	#[Enable/Disable] Bonemeal use on Golden Apple Plants [true/false] | [Default: true]
	allowGoldenBonemeal = true
	#[Enable/Disable] Bonemeal use on Emerald Apple Plants [true/false] | [Default: true]
	allowEmeraldBonemeal = true

["World loot"]
	#[Enable/Disable] Lootable content on Chests [true/false] | [Default: true]
	allowWorldLoot = true

["Apple Tree Generation"]
	NOTE = "Custom biomes may could work, Use: [modid]:[biome_name] | Higher numbers has lesser chance | Unregistered values will be set to Default | Values accepted [1 - 500]"
	#[Enable/Disable] Natural Apple Trees generation [true/false] | [Default: true]
	AllowAppleTrees = true
	#Register the biomes to Spawn Apple Trees
	Locations = ["plains", "sunflower_plains", "flower_forest", "forest", "dark_forest", "wooded_mountains"]
	#Register the Chances of each registered Biome
	Chances = [18, 16, 1, 6, 7, 12]

["Golden Tree Generation"]
	#[Enable/Disable] Natural Golden Trees generation [true/false] | [Default: false]
	AllowGoldenTrees = false
	#Register the biomes to Spawn Golden Trees
	Locations = []
	#Register the Chances of each registered Biome
	Chances = []

["Emerald Tree Generation"]
	#[Enable/Disable] Natural Golden Trees generation [true/false] | [Default: true]
	AllowEmeraldTrees = true
	#Register the biomes to Spawn Golden Trees
	Locations = ["flower_forest"]
	#Register the Chances of each registered Biome
	Chances = [75]

["Biome Config"]
	#Define Apple Forest spawn Value on the overworld
	#Range: 1 ~ 30
	BiomeChance = 5
	Biomes = "[minecraft:the_void, minecraft:plains, minecraft:sunflower_plains, minecraft:snowy_plains, minecraft:ice_spikes, minecraft:desert, minecraft:swamp, minecraft:forest, minecraft:flower_forest, minecraft:birch_forest, minecraft:dark_forest, minecraft:old_growth_birch_forest, minecraft:old_growth_pine_taiga, minecraft:old_growth_spruce_taiga, minecraft:taiga, minecraft:snowy_taiga, minecraft:savanna, minecraft:savanna_plateau, minecraft:windswept_hills, minecraft:windswept_gravelly_hills, minecraft:windswept_forest, minecraft:windswept_savanna, minecraft:jungle, minecraft:sparse_jungle, minecraft:bamboo_jungle, minecraft:badlands, minecraft:eroded_badlands, minecraft:wooded_badlands, minecraft:meadow, minecraft:grove, minecraft:snowy_slopes, minecraft:frozen_peaks, minecraft:jagged_peaks, minecraft:stony_peaks, minecraft:river, minecraft:frozen_river, minecraft:beach, minecraft:snowy_beach, minecraft:stony_shore, minecraft:warm_ocean, minecraft:lukewarm_ocean, minecraft:deep_lukewarm_ocean, minecraft:ocean, minecraft:deep_ocean, minecraft:cold_ocean, minecraft:deep_cold_ocean, minecraft:frozen_ocean, minecraft:deep_frozen_ocean, minecraft:mushroom_fields, minecraft:dripstone_caves, minecraft:lush_caves, minecraft:nether_wastes, minecraft:warped_forest, minecraft:crimson_forest, minecraft:soul_sand_valley, minecraft:basalt_deltas, minecraft:the_end, minecraft:end_highlands, minecraft:end_midlands, minecraft:small_end_islands, minecraft:end_barrens]"

