
["Main Settings Handler"]
	#List of items that will ignite furnace, smoker, or blast furnace blocks. This list will only accept items with durability.
	Furnace_executor_item_list = []
	#Custom item consumption for when the player tries to use the Sparkling Flint item. This value can be empty, just keep the brackets.
	Sparkling_flint_consumption_item = "lititup:switchgrass_fiber"
	#Enable or disable the requirement to ignite a furnace block with flint and steel item before allowing it to cook items.
	Flint_and_steel_furnace_executor = true

["Custom Message"]
	#Personalized message for missing items when using Sparkling Flint item.
	Personalized_Message = "Missing: Switchgrass Fiber!"
	#Before using Personalized_message setting, set the value below to true.
	Use_Personalized_Message = false

